# Generated by Django 3.0.4 on 2020-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='', max_length=20)),
                ('user_name', models.CharField(default='', max_length=90)),
            ],
        ),
    ]
